name: pickrr_app
description: For your logistics and delivery hassles.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flare_flutter: ^2.0.6
  country_code_picker: ^1.1.7
  image_picker: ^0.6.7+12
  flutter_svg: ^0.19.0
  badges: ^1.1.4
  intl: ^0.15.8
  dotted_line: ^2.0.2
  url_launcher: ^5.7.10
  circular_profile_avatar: ^1.0.8
  lite_rolling_switch: ^0.1.1
  flutter_awesome_alert_box: ^1.0.1

  google_maps_flutter: ^0.5.30
  geolocator: ^6.1.7
  google_map_polyline: ^0.2.0
  google_maps_webservice: ^0.0.16
  flutter_google_places: ^0.2.6

  bloc: ^6.1.0
  flutter_bloc: ^6.1.1
  equatable: ^1.2.5
  meta: ^1.2.4
  sqflite: ^1.3.2+1
  dio: ^3.0.10
  flutter_secure_storage: ^3.3.5
  flushbar: ^1.10.4
  flutter_clipboard_manager: ^0.0.2
  web_socket_channel: ^1.1.0
  flutterwave: ^0.0.2
  firebase_messaging: ^7.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/flare/
    - assets/fonts/
    - assets/images/
    - assets/svg/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Light.ttf
          weight: 300

        - asset: assets/fonts/Ubuntu-Regular.ttf
          weight: 400

        - asset: assets/fonts/Ubuntu-Medium.ttf
          weight: 500

        - asset: assets/fonts/Ubuntu-Bold.ttf
          weight: 700
